import type { Metadata } from "next";
import "./globals.css";
import Navigation from "@/components/ui/Navigation";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Navigation />
          <main className="flex justify-center">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
